Import('env')
from os import path

# --------------------------------------------------------------------------
name       = 'arras4_testmessage'
sources    = env.DWAGlob('*.cc')
incdir     = [str(env.Dir('..').srcnode())]
components = [
            'message_api',
            'arras4_log',
            'openssl'
]
# --------------------------------------------------------------------------
publicHeaders = [
    'TestMessage.h'
]
env.DWAInstallInclude(publicHeaders, 'messages/testmessage')

env.DWAUseComponents(components)
lib = env.DWASharedLibrary(name, sources)
target = env.DWAInstallLib(lib)
env.DWAComponent(name, LIBS=target, CPPPATH=incdir, COMPONENTS=components)
env.DWAInstallSConscriptStub(
    name, LIBS=target, CPPPATH=[env.Dir('$INSTALL_DIR/include')],
    COMPONENTS=components)
env.DWALinkValidate(name)
