Import('env')
from os import path

# --------------------------------------------------------------------------
name       = 'arras4_http'
sources    = env.DWAGlob('*.cc')
incdir     = [str(env.Dir('..').srcnode())]
components = [
    'arras4_network',
    'curl_no_ldap'
]

# --------------------------------------------------------------------------

publicHeaders = [
    'HttpException.h',
    'HttpRequest.h',
    'HttpResponse.h',
    'http_types.h'
]
env.DWAInstallInclude(publicHeaders, 'http')

env.DWAUseComponents(components)
lib = env.DWASharedLibrary(name, sources)
target = env.DWAInstallLib(lib)
env.DWAComponent(name, LIBS=target, CPPPATH=incdir, COMPONENTS=components)
env.DWAInstallSConscriptStub(
    name, LIBS=target, CPPPATH=[env.Dir('$INSTALL_DIR/include')],
    COMPONENTS=components)
env.DWALinkValidate(name)
