Import('env')
from os import path

# --------------------------------------------------------------------------
name       = 'chunking'
sources    = env.DWAGlob('*.cc')
incdir     = [str(env.Dir('..').srcnode())]
components = [
    'arras4_log',
    'arras4_exceptions',
    'message_api',
    'arras4_network',
    'jsoncpp'
]
# --------------------------------------------------------------------------

publicHeaders = [
    'ChunkingConfig.h',
    'ChunkingMessageEndpoint.h',
    'MessageUnchunker.h',
    'MessageChunk.h'
]
env.DWAInstallInclude(publicHeaders, 'chunking')

env.DWAUseComponents(components)
lib = env.DWASharedLibrary(name, sources)
target = env.DWAInstallLib(lib)
env.DWAComponent(name, LIBS=target, CPPPATH=incdir, COMPONENTS=components)
env.DWAInstallSConscriptStub(
    name, LIBS=target, CPPPATH=[env.Dir('$INSTALL_DIR/include')],
    COMPONENTS=components)
env.DWALinkValidate(name)
