Import('env')
from os import path

# --------------------------------------------------------------------------
name       = 'arras4_testcomputation'
sources    = env.DWAGlob('*.cc')
incdir     = [str(env.Dir('..').srcnode())]
components = [
    'arras4_log',
    'message_api',
    'computation_api',
    'arras4_testmessage',
    'jsoncpp'
]
# --------------------------------------------------------------------------

#publicHeaders = [
#]
#env.DWAInstallInclude(publicHeaders, 'testcomputation')

env.DWAUseComponents(components)
lib = env.DWASharedLibrary(name, sources, NO_VARIANT_NAME=True)
target = env.DWAInstallDso(lib)
env.DWAComponent(name, LIBS=target, CPPPATH=incdir, COMPONENTS=components)
env.DWALinkValidate(name)
