Import('env')
from os import path

modName = path.basename(path.abspath('..'))
libName = path.basename(path.abspath('.'))
# --------------------------------------------------------------------------
name       = 'arras4_log'
sources    = env.DWAGlob('*.cc')
incdir     = [str(env.Dir('..').srcnode())]
components = []
# --------------------------------------------------------------------------
publicHeaders = [
   'AutoLogger.h', 
   'ConsoleLogger.h',
   'LogEventStream.h',
   'Logger.h',
   'StreamLogger.h',
   'SyslogLogger.h'
]
env.DWAInstallInclude(publicHeaders, 'arras4_log')
env.DWAUseComponents(components)
env.Prepend (CPPPATH=incdir)
lib = env.DWASharedLibrary(name, sources)
target = env.DWAInstallLib(lib)
env.DWAComponent(name, LIBS=target, CPPPATH=incdir, COMPONENTS=components)
env.DWAInstallSConscriptStub(
    name, LIBS=target, CPPPATH=[env.Dir('$INSTALL_DIR/include')],
    COMPONENTS=components)
env.DWALinkValidate(name)
