Import('env')
import os

# --------------------------------------------------------------------------
name       = 'execute'
sources    = env.DWAGlob('*.cc')
incdir     = [str(env.Dir('..').srcnode())]
components = [
    'arras4_log',
    'message_api',
    'jsoncpp'
]
# --------------------------------------------------------------------------

publicHeaders = [
    'ControlGroup.h',
    'Environment.h',
    'IoCapture.h',
    'MemoryTracking.h',
    'Process.h',
    'process_utils.h',
    'ProcessController.h',
    'ProcessManager.h',
    'RezContext.h',
    'ShellContext.h',
    'SpawnArgs.h'
]

env.DWAInstallInclude(publicHeaders, 'execute')

if os.path.isfile('/usr/lib64/libcgroup.so'):
    env.AppendUnique(LIBS = ['cgroup'])
    env.AppendUnique(CPPDEFINES=['ARRAS_ENABLE_CGROUP'])

env.DWAUseComponents(components)
lib = env.DWASharedLibrary(name, sources)
target = env.DWAInstallLib(lib)
env.DWAComponent(name, LIBS=target, CPPPATH=incdir, COMPONENTS=components)
env.DWAInstallSConscriptStub(
    name, LIBS=target, CPPPATH=[env.Dir('$INSTALL_DIR/include')],
    COMPONENTS=components)
env.DWALinkValidate(name)
