Import('env')
from os.path import join


name = "time_example_client"
sources = env.DWAGlob('*.cc')

# expose the current directory as the include path
include_paths = ['${INSTALL_DIR}/include']

# Components needed to build/use this library.
components = [
    'sdk',
    'message_api',
    'client_api',
    'time_example_message',
    'boost_program_options_mt',
    'boost_system_mt',
    'jsoncpp'
]

env.DWAUseComponents(components)
env.AppendUnique(CPPPATH = [env.Dir('.').srcnode()],)

prog = env.DWAProgram(name, sources)
env.DWAInstallBin(prog)
