Import('env')
from os import path

# --------------------------------------------------------------------------
name       = 'client_local'
sources    = env.DWAGlob('*.cc')
incdir     = [str(env.Dir('..').srcnode())]
components = [
    'arras4_log',
    'arras4_athena',
    'message_api', 
    'execute',
    'arras4_network',
    'jsoncpp',
    'boost_headers'
]
# --------------------------------------------------------------------------

publicHeaders = [
    'LocalSession.h',
    'LocalSessions.h',
    'SessionError.h',
    'SessionNotification.h'
    
]

env.DWAInstallInclude(publicHeaders, 'client/local')

env.DWAUseComponents(components)
lib = env.DWASharedLibrary(name, sources)
target = env.DWAInstallLib(lib)
env.DWAComponent(name, LIBS=target, CPPPATH=incdir, COMPONENTS=components)
env.DWAInstallSConscriptStub(
    name, LIBS=target, CPPPATH=[env.Dir('$INSTALL_DIR/include')],
    COMPONENTS=components)
env.DWALinkValidate(name)
