Import('env')
from os import path

# --------------------------------------------------------------------------
name       = 'core_messages'
sources    = env.DWAGlob('*.cc')
incdir     = [str(env.Dir('..').srcnode())]
components = [
            'message_api',
            'jsoncpp'
]
# --------------------------------------------------------------------------
publicHeaders = [
    'ControlMessage.h',
    'EngineReadyMessage.h',
    'ExecutorHeartbeat.h',
    'SessionStatusMessage.h',
    'PingMessage.h',
    'PongMessage.h'
]
env.DWAInstallInclude(publicHeaders, 'core_messages')

env.DWAUseComponents(components)
lib = env.DWASharedLibrary(name, sources)
target = env.DWAInstallLib(lib)
env.DWAComponent(name, LIBS=target, CPPPATH=incdir, COMPONENTS=components)
env.DWAInstallSConscriptStub(
    name, LIBS=target, CPPPATH=[env.Dir('$INSTALL_DIR/include')],
    COMPONENTS=components)
env.DWALinkValidate(name)

