Import('env')
from os import path

# --------------------------------------------------------------------------
name       = 'arras4_athena'
libname    = 'arras4_athena'
sources    = env.DWAGlob('*.cc')
incdir     = [str(env.Dir('..').srcnode())]
components = [
                'boost_date_time_mt',
                'boost_headers',
                'boost_system_mt',
                'arras4_log'      
             ]
# --------------------------------------------------------------------------
publicHeaders = [
    'AthenaLogger.h',
    'UdpSyslog.h'
]
env.DWAInstallInclude(publicHeaders, 'arras4_athena')
env.DWAUseComponents(components)
env.Prepend (CPPPATH=incdir)
lib = env.DWASharedLibrary(name, sources)
target = env.DWAInstallLib(lib)
env.DWAComponent(name, LIBS=target, CPPPATH=incdir, COMPONENTS=components)
env.DWAInstallSConscriptStub(
    name, LIBS=target, CPPPATH=[env.Dir('$INSTALL_DIR/include')],
    COMPONENTS=components)
env.DWALinkValidate(name)
