Import('env')
from os import path

# --------------------------------------------------------------------------
name       = 'shared_impl'
sources    = env.DWAGlob('*.cc', exclude = ['Platform_Android.cc', 'Platform_Windows.cc'])
incdir     = [str(env.Dir('..').srcnode())]
components = [
    'message_api',
    'computation_api',
    'arras4_exceptions',
    'arras4_network',
    'message_impl',
    'jsoncpp',
    'arras4_log',
    'uuid'
]
# --------------------------------------------------------------------------

publicHeaders = [
    'ConfigurationError.h',
    'ExecutionLimits.h',
    'DispatcherExitReason.h',
    'MessageDispatcher.h',
    'MessageHandler.h',
    'MessageQueue.h',
    'Platform.h',
    'ProcessExitCodes.h',
    'RegistrationData.h',
    'ThreadsafeQueue.h',
    'ThreadsafeQueue_impl.h'
]
env.DWAInstallInclude(publicHeaders, 'shared_impl')

env.DWAUseComponents(components)
lib = env.DWASharedLibrary(name, sources)
target = env.DWAInstallLib(lib)
env.DWAComponent(name, LIBS=target, CPPPATH=incdir, COMPONENTS=components)
env.DWAInstallSConscriptStub(
    name, LIBS=target, CPPPATH=[env.Dir('$INSTALL_DIR/include')],
    COMPONENTS=components)
env.DWALinkValidate(name)
