# This template is configured for default settings that will launch a pipeline
# for release of a rez-2 build whenever a push happens on the main, master or
# release branches. For alternative setups, please read the following wiki: 
# http://mydw.dreamworks.net/display/SCM/Configuring+Harmony+Pipeline+Trigger+Github+Actions
#
# You may delete this comment block.
#
name: Harmony Pipeline CD Trigger

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
      - '**.md'
      - '.github/**'
      - 'flowpipeline.yaml'
      - 'pull_request_template.md'
  workflow_dispatch:

jobs:
   call_workflow:
    uses: dwanim/.github/.github/workflows/Harmony_CICD.yml@master
    with:
      pipe_config: 'release'
      rez_config: 'rez-2'
