Import('env')
from os.path import join


name = 'arras4test'
sources = env.DWAGlob('*.cc')

# expose the current directory as the include path
include_paths = ['${INSTALL_DIR}/include']

# Components needed to build/use this library.
components = [
    # Arras deps
    'sdk',
    'message_api',
    'computation_api',
    'arras4_http',
    'arras4_log',
    'client_api',
    'arras4_testmessage',

    # Third party 
    'jsoncpp',
    'boost_headers',
    'boost_chrono_mt',
    'boost_program_options_mt',
    'boost_system_mt'
]

env.DWAUseComponents(components)
env.AppendUnique(LIBS = ['dl'])
env.AppendUnique(CPPPATH = [env.Dir('.').srcnode()],)

prog = env.DWAProgram(name, sources)
env.DWAInstallBin(prog)
