Import('env')
from os import path

# --------------------------------------------------------------------------
name       = 'routing'
sources    = env.DWAGlob('*.cc')
incdir     = [str(env.Dir('..').srcnode())]
components = [
    'message_api',
    'arras4_exceptions',
    'arras4_log',
    'jsoncpp',
    'uuid'
]
# --------------------------------------------------------------------------

publicHeaders = [
    'ComputationMap.h',
    'Addresser.h',
    'Addressing.h'
]
env.DWAInstallInclude(publicHeaders, 'routing')

env.DWAUseComponents(components)
lib = env.DWASharedLibrary(name, sources)
target = env.DWAInstallLib(lib)
env.DWAComponent(name, LIBS=target, CPPPATH=incdir, COMPONENTS=components)
env.DWAInstallSConscriptStub(
    name, LIBS=target, CPPPATH=[env.Dir('$INSTALL_DIR/include')],
    COMPONENTS=components)
env.DWALinkValidate(name)
